# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: '$(Build.SourcesDirectory)/forum-app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './forum-app/build'
    ArtifactName: 'build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: './forum-app/build'
    skip_app_build: true
    skip_api_build: true
    azure_static_web_apps_api_token: 'e8440a38ae4419c6e11d82f7d3b6faf7031c8c5c9f0db039bec18c17ecf959253-c6d8b40b-440c-4d78-8a0f-9ac11fe63418010235958'